// src/pages/Games/Hangman/words.js

const WORD_BANK = {
  frontend: [
    "COMPONENT","USESTATE","USEFFECT","PROPS","CONTEXT",
    "REDUCER","MIDDLEWARE","SELECTOR","DISPATCH","HYDRATION",
    "SUSPENSE","LAZY","MEMO","CALLBACK","PORTAL",
    "TYPESCRIPT","INTERFACE","GENERIC","NARROWING","ASSERTION",
    "TAILWIND","FLEXBOX","GRID","ANIMATION","TRANSFORM",
    "WEBPACK","BUNDLER","TREESHAKING","CODESPLIT","MINIFY",
    "PROMISE","ASYNC","AWAIT","CLOSURE","PROTOTYPE",
    "VIRTUAL","DIFFING","RECONCILE","FIBER","CONCURRENT",
  ],
  general: [
    "JAVASCRIPT","FRAMEWORK","DEVELOPER","ALGORITHM","DATABASE",
    "DEBUGGING","REFACTOR","FUNCTION","VARIABLE","CONSTANT",
    "TERMINAL","KEYBOARD","MONITOR","NETWORK","PROTOCOL",
    "SECURITY","PASSWORD","ENCRYPT","FIREWALL","VULNERABILITY",
    "ABSTRACT","INHERIT","POLYMORPHISM","ENCAPSULATE","INTERFACE",
  ],
};

export function getWord(category = "frontend") {
  const bank = WORD_BANK[category] ?? WORD_BANK.frontend;
  return bank[Math.floor(Math.random() * bank.length)];
}

export const CATEGORIES = Object.keys(WORD_BANK);
